### PR TITLE
feat: add web support

### PR DESCRIPTION
**Pull request by micaelcid**
# Description

🚧 Work In Progress 🚧 

I only added a few basic functionalities, so we can use Instana in a Flutter Web application.

### CODE REVIEW

**Comment by filpano** [comment]
Hi, is this still open? What still needs doing to get flutter web support?

**Comment by micaelcid** [comment]
> Hi, is this still open? What still needs doing to get flutter web support?

Hey, @filpano. Sorry for the late response. Left this open as a reference but never got back to it.

I confess I am not a heavy Instana user, so I only added support to very few basic methods (mostly custom events) as you can see. The current functionalities have been working very well since then.

Which [Website APIs](https://www.ibm.com/docs/en/instana-observability/current?topic=websites-javascript-agent-api) do you need?

**Comment by micaelcid** [comment]
@filpano just reverted some downgrade I did and made a small adjustment to make the example app runnable on the web, in case you're still interested.

**Comment by FabioNieVec** [comment]
Hey, is there a possibility to update the go_route package? Its very old

**Pull request closed without merging**
